package PasswordPhilosphy;

public class Input {
    public static String input="16-18 h: hhhhhhhhhhhhhhhhhh\n" +
            "17-18 d: ddddddddddddddddzn\n" +
            "15-18 c: cccccccccccccczcczc\n" +
            "3-9 r: pplzctdrc\n" +
            "4-14 d: lxdmddfddddddd\n" +
            "8-14 v: pvxlknfvplgktv\n" +
            "11-13 h: hphhhhhhhfhshhhhh\n" +
            "1-4 l: hbljb\n" +
            "1-2 x: wxqzlvt\n" +
            "1-5 g: dxggdggb\n" +
            "5-13 f: lfgdplfffxffswck\n" +
            "6-7 z: zzzzgzzzz\n" +
            "1-7 c: cccclcchrkctfhc\n" +
            "3-7 c: ccjccqzcc\n" +
            "15-16 x: rxxchpvgxxhxkxxw\n" +
            "3-5 h: hbxjg\n" +
            "3-7 q: sffnxxqvdfsnqlhqpq\n" +
            "8-11 h: hhhhhhhlhhh\n" +
            "7-8 w: bxwzdlwr\n" +
            "4-5 x: xxxxp\n" +
            "4-7 x: xxxxxxxx\n" +
            "2-18 l: lllllllllllllllllrll\n" +
            "6-10 n: nnnnnngnznn\n" +
            "12-13 c: ccccccccccchc\n" +
            "2-6 g: ggqngxgbggc\n" +
            "4-5 k: xdztx\n" +
            "4-9 m: txskmsnxvqjhlp\n" +
            "9-11 w: wwtxmsjwjwlw\n" +
            "12-16 g: cgggpkhggqkgrjcbx\n" +
            "9-11 s: sxsssmssvszs\n" +
            "17-18 c: cccccccccclccsccchcc\n" +
            "7-8 z: stpgzwlqm\n" +
            "9-19 q: qqqqqqqqqqqqqqqqqqqq\n" +
            "4-5 p: hpvtpfgwp\n" +
            "8-9 m: mmmmmmqmm\n" +
            "11-12 s: ssswsssssspts\n" +
            "2-4 j: jjdr\n" +
            "17-18 k: kvkkmlkkkkkkfklkkkkk\n" +
            "1-4 b: bbbwb\n" +
            "2-12 c: cccccccccccccc\n" +
            "14-15 l: llllllllllplllllllll\n" +
            "7-10 c: czcccsvnrbccc\n" +
            "11-12 d: nfmvdlxbfwzq\n" +
            "8-10 t: tvtttttzts\n" +
            "5-6 g: wggghg\n" +
            "11-16 d: ztfdkggclvzmvsxd\n" +
            "16-17 v: vvvvvvbvvpvxvvvhv\n" +
            "3-7 w: vrswklnfnjzkm\n" +
            "1-18 s: bsssssssssssssssshss\n" +
            "8-10 g: vdzldttzgm\n" +
            "19-20 n: nnnnnnnnnnnnnnnnnnrb\n" +
            "1-4 x: xxxqxxxxx\n" +
            "11-13 m: xmmxmmmmgmwmmm\n" +
            "4-5 j: pzfjjsjjmcm\n" +
            "1-7 j: jsjsmjj\n" +
            "7-8 j: nqkkljhbj\n" +
            "4-5 w: wmsbqhmwdjns\n" +
            "4-7 j: jbjjcjcf\n" +
            "2-7 f: jhsxldwf\n" +
            "3-4 f: vmff\n" +
            "5-7 z: fscmzjqs\n" +
            "2-10 g: ggtfwzpbkgqqlzwmbm\n" +
            "5-6 j: jjwbdjj\n" +
            "13-15 b: bbbbbbbbkbbbvbbbb\n" +
            "4-6 t: qdthtt\n" +
            "1-8 m: kmmmmmmvmmmmm\n" +
            "4-8 g: gbgqgtcglvgggcg\n" +
            "3-4 h: ghjn\n" +
            "3-8 b: mgbzbjvbkbpbd\n" +
            "11-17 k: kkkktskgkkkfgzkkk\n" +
            "1-6 f: ftnvfgtrlcs\n" +
            "3-13 r: hrrzrfrfpvdlrnrcrcs\n" +
            "3-8 l: gzljpllvl\n" +
            "3-11 h: hchjhhnhhnhvhhhhx\n" +
            "9-16 s: srssssssssskpldsqss\n" +
            "4-10 n: nnbnnnwnnwnnnxnn\n" +
            "3-4 n: nnnp\n" +
            "11-19 z: nznpcdnxkwznzlpvcwzj\n" +
            "4-7 w: wwwrwtwncwvwwwwx\n" +
            "3-4 s: bkgs\n" +
            "2-16 z: nzlcmlvqdcmmcnphb\n" +
            "1-15 z: zzzzzzzzzzzzzzzzzz\n" +
            "9-10 t: tmgttdtqtttttwbgttt\n" +
            "1-2 h: hhhhhmhmkgxhnhw\n" +
            "4-5 h: hlhhh\n" +
            "9-15 h: xhhhhhchhhznphh\n" +
            "5-8 w: jwphwwwj\n" +
            "4-5 z: lztsz\n" +
            "10-11 c: mhtdcdhggccgfck\n" +
            "3-8 t: ccttgcktz\n" +
            "1-12 m: smmmmxmmmgmx\n" +
            "1-12 r: srrrrrrrrrrlrrrrr\n" +
            "2-5 h: khhzhrqr\n" +
            "3-4 m: mmztmm\n" +
            "2-5 f: fbffqf\n" +
            "1-11 p: zpppppppnphppx\n" +
            "5-12 z: pqrzlwztvzjfzbt\n" +
            "8-12 b: bbbbbbbdbbbcb\n" +
            "3-4 g: ghqg\n" +
            "7-10 m: mmmmmmmmmmmm\n" +
            "5-14 q: jblkqbqpmqwsqt\n" +
            "6-8 r: rrrtrlzltfrrrgrr\n" +
            "9-14 r: rrrrrzrrjrrrgmr\n" +
            "9-10 m: tmshdggksmv\n" +
            "10-17 d: dddddddddcddddddf\n" +
            "6-7 f: ffffffx\n" +
            "9-19 j: jfjljzjcjjzjjjfjpjj\n" +
            "2-6 h: jhxmhh\n" +
            "1-7 g: wgggggzggxmggg\n" +
            "5-6 n: nlgnlx\n" +
            "4-7 t: thzttttt\n" +
            "4-6 x: xhnxjx\n" +
            "14-16 p: ppppppppppppppppp\n" +
            "2-4 s: ssps\n" +
            "7-15 k: bzfljhskslxlznwvphg\n" +
            "6-7 j: dkjjsgk\n" +
            "9-11 p: ppppppppkpmpp\n" +
            "5-8 t: tzcttttttt\n" +
            "8-11 d: dddddddgddld\n" +
            "3-9 w: dwwhwbwwwwwzwtwxw\n" +
            "2-3 x: xxwxmw\n" +
            "1-5 g: gdlvg\n" +
            "4-6 c: cccmcrccccccc\n" +
            "1-11 f: ffffffffffnff\n" +
            "10-11 l: lgqgnwlhgdlvdlv\n" +
            "3-7 v: cjvvvvnvjvjvgvkx\n" +
            "4-5 v: vvvsv\n" +
            "13-15 t: tttttrtttttttth\n" +
            "11-12 q: nccsqqhqqqqqlqqqqq\n" +
            "2-7 p: pspppppppp\n" +
            "4-6 g: gglggg\n" +
            "17-18 p: hwpkcxvppzxxvpjzpp\n" +
            "1-3 b: dlfz\n" +
            "11-12 p: ppppppppppfpdppp\n" +
            "1-2 s: ssszdss\n" +
            "2-15 b: nbsblthmngvbqvbh\n" +
            "1-6 q: sqqqqbqq\n" +
            "4-11 q: tgmtqqrxfsvrzhc\n" +
            "8-13 q: qqqqzqqqqqqmqqqjqq\n" +
            "9-17 n: nnnnnnnnnnnnnnnnpnnn\n" +
            "6-9 h: rmhrlkhskbhhq\n" +
            "5-6 n: qnnjnn\n" +
            "4-6 l: lxlllkvdltgcfl\n" +
            "12-15 f: fflffffpfvftffwff\n" +
            "13-16 t: fpwmwmvtqbvxtvtt\n" +
            "7-8 w: kwwwjgwmwbw\n" +
            "1-2 x: xxnvmbcmxhnkkgfrr\n" +
            "3-7 f: rpcnzvjgh\n" +
            "13-15 r: rrwrkrrrrrrrdrbr\n" +
            "11-13 h: ghnzvhhhhwhchmh\n" +
            "7-8 h: hhhhhhnv\n" +
            "5-6 l: kgllll\n" +
            "1-4 k: kqsjblck\n" +
            "6-8 c: crxxccccgc\n" +
            "2-13 g: fvmhpbqkgvbwqvbldb\n" +
            "4-7 g: ggglggmgggkggg\n" +
            "6-7 n: znnrnpnn\n" +
            "12-15 j: jjqjzjjchjmjzsgppss\n" +
            "4-5 k: kkkkk\n" +
            "12-16 r: rrrrrrrrrrrcrrznrz\n" +
            "10-12 w: hdwsvqpwzvtx\n" +
            "9-11 b: brbtbwbbjbbbbbb\n" +
            "6-8 q: nqkvkqdqrq\n" +
            "3-5 n: pjcnd\n" +
            "9-11 q: qqqqqqqqpqqqq\n" +
            "6-7 b: zdbbfpqbvbbgbnq\n" +
            "11-14 g: dxvgpggnpngpqgn\n" +
            "8-11 z: zzzzzzzczzq\n" +
            "8-18 z: nzczzlkcchpzdkrpvzrd\n" +
            "2-4 d: fwdhl\n" +
            "12-13 m: mmmqllmmmmhnf\n" +
            "6-8 b: bmbbcbbbznnbd\n" +
            "18-19 z: zkzzzzzzzzzzzzzzzzz\n" +
            "4-10 m: smkkrpqznmnfdprq\n" +
            "7-8 j: jjjjjjhsj\n" +
            "10-15 t: trpttgcttttttbtt\n" +
            "6-7 t: tttttltttttttt\n" +
            "7-13 x: bxxcxxvxknqcxsx\n" +
            "6-10 j: zjrrtjwxfjhhtcsktslf\n" +
            "3-5 m: zjmms\n" +
            "11-14 v: vvvvvvvkvvvvvvv\n" +
            "1-2 c: ccch\n" +
            "13-14 v: vvvsvvvvvvvvvv\n" +
            "9-12 g: fgkgxgggcjdg\n" +
            "4-6 t: ttpxtgntzwtx\n" +
            "10-12 g: gggggggggkgbg\n" +
            "1-3 l: llllw\n" +
            "7-12 d: nddvldndjcdpdddz\n" +
            "2-5 w: wwtlwwvdww\n" +
            "6-11 c: fcccccccdcc\n" +
            "12-19 s: sjsssssssssssshssss\n" +
            "19-20 t: ttttttttttttttttttkf\n" +
            "7-11 z: zpfgzczcxzmclzzz\n" +
            "2-7 d: sddlpvdqzzlqfkjkbb\n" +
            "2-7 k: dkmlkckm\n" +
            "4-8 w: wwwwwwswww\n" +
            "1-3 d: pddd\n" +
            "1-9 r: chrrrrrrr\n" +
            "17-19 t: ttttttttttttttttptvt\n" +
            "17-18 v: xvvvkvvvvxvsvhbvvv\n" +
            "6-11 j: njjjjcpjjjbjhqj\n" +
            "1-3 s: ssss\n" +
            "15-16 k: kkkckkqgkkxkkkrp\n" +
            "6-7 b: mgzhbbb\n" +
            "9-12 w: wjwxwwpxxtwvwwjnnw\n" +
            "2-5 x: xxlwcpzfx\n" +
            "4-11 j: jjjxjjjjjjcj\n" +
            "6-17 c: qcccsvvzfpccccfchcc\n" +
            "3-4 c: scbjdmjhtlcdvbq\n" +
            "8-9 b: fngpbvfsctl\n" +
            "15-16 r: rrrrrrrqrrrrrrdlt\n" +
            "5-10 v: tvqlvvvtrvlfkwsvlvn\n" +
            "6-8 q: qqsqfqqqq\n" +
            "8-9 m: mmmmmmmms\n" +
            "8-12 r: rxrrprvcrrjd\n" +
            "19-20 c: cncccqwnbsvccclcjkcc\n" +
            "2-4 b: mmjg\n" +
            "12-13 l: slwjlqlslllll\n" +
            "2-8 m: fmmppmmmmtmzmmmm\n" +
            "4-13 l: llllmllllllllltz\n" +
            "6-11 f: ffffffhtffff\n" +
            "1-6 g: gngfzbgx\n" +
            "1-5 f: fwfmfrfxf\n" +
            "16-17 t: ttttttttttttttttt\n" +
            "2-7 w: twsdwvj\n" +
            "6-13 m: mmksmfnmdxtmhmmxm\n" +
            "1-6 b: bbbjbbnbzwgrb\n" +
            "13-15 c: ccccccccccccccsccc\n" +
            "7-8 k: kskkkgkkk\n" +
            "6-7 g: gggmgbzg\n" +
            "17-18 k: mckjkfkdfqkxgtrcrch\n" +
            "4-5 g: xglggggs\n" +
            "2-4 d: ddddddd\n" +
            "5-7 s: nlpzsss\n" +
            "5-12 w: ngwpwprvlftr\n" +
            "15-17 p: psgjvphpbppzpprpp\n" +
            "1-5 m: lljdr\n" +
            "6-8 h: hnzhhqxh\n" +
            "4-7 g: mmccqwfvlqrks\n" +
            "12-14 l: lllllllllllllll\n" +
            "2-3 c: cqfc\n" +
            "15-16 z: zzzzzzzzzzzzzzzz\n" +
            "6-7 v: gkzxvvvdbvnp\n" +
            "7-8 z: zzzjzzvc\n" +
            "13-18 v: vvvvvvvvvvvvkvvvvlv\n" +
            "1-12 p: pppppppkppppppp\n" +
            "10-12 v: vvvvvvvvvtvvv\n" +
            "5-6 s: qkpsqz\n" +
            "5-6 t: tgthtlt\n" +
            "1-5 z: zzzzzz\n" +
            "6-7 j: jjjjjjhj\n" +
            "4-5 b: lbbqdfrbbv\n" +
            "4-6 n: jvmxtfwnqpdhn\n" +
            "2-5 r: mcmrf\n" +
            "8-10 s: sssssssggsss\n" +
            "6-9 f: ffbflgzsfftxqg\n" +
            "1-18 p: pppppppppppppppppp\n" +
            "3-13 b: bbbbdfbbbbbnbbbblcb\n" +
            "5-6 d: drddpk\n" +
            "4-5 h: jhhhdh\n" +
            "12-18 x: wxtsqsrxtsxxxvhxfxx\n" +
            "5-6 q: qmxdnz\n" +
            "6-16 q: qqwqfqqqzqqqqfqqq\n" +
            "4-10 x: xxxgxxxznx\n" +
            "2-3 x: xndnnb\n" +
            "4-5 g: hcgff\n" +
            "5-6 s: wsgjpgssssssdssssss\n" +
            "16-18 k: kkkkkkkkkkkkkkkkkk\n" +
            "5-6 k: kkkkpqkk\n" +
            "13-19 r: rrrrrrrrgrkrrrrrrrr\n" +
            "10-11 s: vgnbshssjcpss\n" +
            "3-5 f: qfhjmjkcgv\n" +
            "3-4 q: nrtnvbsmbwpq\n" +
            "8-18 j: jjjrjjdtjmjjkjwzjjk\n" +
            "4-14 t: tttgtttttttbtxt\n" +
            "5-6 q: qqqqtj\n" +
            "14-17 b: bbbbbhjffbbtbbbbb\n" +
            "9-18 x: rxxxwxxxxxxxxxxxxc\n" +
            "3-9 f: hgjjfkvlflhbtxpb\n" +
            "7-19 n: nnmndnknnlnjnnnnnnz\n" +
            "5-8 m: mbmlmmfpgmwmm\n" +
            "7-8 j: jjjjjsdkjg\n" +
            "3-8 p: hlpjkpjjvbrgpw\n" +
            "10-11 t: tttttttttptt\n" +
            "6-10 b: bbbbbthbbd\n" +
            "3-11 l: xvlknhhglhcgvk\n" +
            "7-17 j: mpxjmcwwqqjtprwgjj\n" +
            "14-17 v: vvvvvvvvsvvvvhvvvv\n" +
            "16-17 p: pppppppdpwpppppppp\n" +
            "3-4 h: hhdr\n" +
            "8-9 v: bvvvvvvfs\n" +
            "6-12 p: pdpppbppnqpxp\n" +
            "3-6 w: jlwwjvcwwhwjrgwzjkqw\n" +
            "3-4 c: zqkzcc\n" +
            "2-7 h: hzhhhhv\n" +
            "1-9 g: mgjlggdznj\n" +
            "3-6 x: nxjxxkxhfx\n" +
            "7-11 m: pmpmmmmmmmmmtmm\n" +
            "9-11 t: tttttttttttt\n" +
            "3-4 n: nnnpqnbfnnnzn\n" +
            "10-17 b: bbqbbbjbbhbbgbthxb\n" +
            "2-8 n: qfqnjhhjsvcvcnnjnnhn\n" +
            "3-6 n: jsgnnn\n" +
            "1-2 n: nntknsnsp\n" +
            "5-7 s: ssssssss\n" +
            "8-9 l: kllllllllh\n" +
            "4-9 k: vkkkkkkkkk\n" +
            "3-8 x: hxdxbxnmxx\n" +
            "5-8 f: pfmvlbffff\n" +
            "13-18 n: rnncfnnntnrgxnnsnn\n" +
            "1-2 d: jxdd\n" +
            "3-5 p: bcfdp\n" +
            "2-4 k: hklkk\n" +
            "13-17 w: wwwwxwwwwldwwwwwm\n" +
            "4-5 z: gzzzgczz\n" +
            "14-15 g: gggggggggggggqg\n" +
            "9-10 x: jzwnmqhgqkxhxb\n" +
            "3-4 z: fszz\n" +
            "13-14 l: nlllllllllrlflllx\n" +
            "1-3 r: rrrr\n" +
            "15-16 c: ccccccckcccccccccl\n" +
            "1-6 h: hhhhhhhphhhhjfhhwjh\n" +
            "5-7 r: gvcprfrrgtqjkgsbcb\n" +
            "12-14 v: vvvhvvvvvvvvvvvvv\n" +
            "18-19 l: llllllrllllllllllpgd\n" +
            "13-14 x: xxxxxxxxxxxxxxx\n" +
            "7-13 d: pcgbdmkhnnxqdhb\n" +
            "9-11 c: ccccccccjcf\n" +
            "14-17 m: mmmmmmmmmmmsmmmkmkm\n" +
            "7-16 p: jblsmjhskpmcflvzqbb\n" +
            "1-3 p: pqpzfpw\n" +
            "6-8 h: whhtglkhshhzhh\n" +
            "1-9 x: xxjxxxxxxxx\n" +
            "2-3 d: ddgwh\n" +
            "3-4 z: rzzz\n" +
            "12-13 p: ppppppppppppppkp\n" +
            "2-6 f: fbffjbxz\n" +
            "4-7 f: dmkrhsfnffg\n" +
            "4-6 p: ppppppppp\n" +
            "17-19 d: ddnwdddddddnddddndgd\n" +
            "4-8 n: bxchqdknggfjqzcvdwzv\n" +
            "3-19 z: zzzzzzzzzzzzzzzzzzpz\n" +
            "2-11 h: hhthvhrhpkhfrljhf\n" +
            "7-8 s: sssssgsg\n" +
            "1-3 p: hpsp\n" +
            "4-5 d: wdkdd\n" +
            "2-4 j: fjpd\n" +
            "2-8 l: dsvhdlpl\n" +
            "11-15 b: bkbbqpbqbbbbbbfbr\n" +
            "4-9 j: vffrxjvglzq\n" +
            "17-19 q: qqqqqqqqqqqqqqqqqqqq\n" +
            "2-9 g: sbpcvnmsghrm\n" +
            "3-6 r: kxwwnfbqv\n" +
            "9-12 w: qxwwwwdwwcww\n" +
            "4-8 t: tttztttxt\n" +
            "5-6 k: sklmkk\n" +
            "1-15 t: qttstmlgtxjfwthj\n" +
            "12-15 s: sssssssssssssssss\n" +
            "1-8 d: ddtddbddj\n" +
            "7-14 m: rmmhmmmmzvmmmkxmmmdm\n" +
            "5-6 n: nnnnnwn\n" +
            "7-8 m: mmmmmmghmm\n" +
            "1-3 q: qpqqgkc\n" +
            "3-10 q: qqqqqzqqqqqqb\n" +
            "1-7 p: ppppppqp\n" +
            "3-5 c: nbkfmcccpkjccv\n" +
            "14-15 q: qqqqxqqqqqqqqqq\n" +
            "8-9 p: plgpblsfp\n" +
            "10-13 w: wwtwwwwwwwwvwww\n" +
            "8-15 k: kkwjkkkknkdkkkkk\n" +
            "6-7 l: lllllmkl\n" +
            "8-9 l: lllllllxgl\n" +
            "10-12 p: gpmpppppppvpvpqpx\n" +
            "4-7 x: rxbxxxzqx\n" +
            "1-10 h: dhhhhhhhhxh\n" +
            "12-18 v: vnwvgvprbfgvvgnvvv\n" +
            "4-17 n: xbdnmnrrcfmczhjxndr\n" +
            "8-9 k: kkkkkckqskkk\n" +
            "9-12 l: rblxmkxmlfflnfpg\n" +
            "6-11 q: vqlqqqqqqqqqqqqnq\n" +
            "8-10 j: lxpjjjjjwjglcjhjjj\n" +
            "4-6 x: xtxxjx\n" +
            "1-2 w: wwwww\n" +
            "5-8 h: hhhhkhjhhwh\n" +
            "7-10 s: stjsssdssdl\n" +
            "2-12 p: xwnzxpzwnxzc\n" +
            "4-5 v: vkvvvvk\n" +
            "1-6 k: ksgmxkkdcfqgxcxm\n" +
            "16-17 g: ggggggggggggggggg\n" +
            "9-10 g: ggggggggmcg\n" +
            "9-12 m: mmmmjzmpmmmx\n" +
            "2-3 r: lrrlrtmbcl\n" +
            "2-3 s: sqss\n" +
            "9-11 k: kkkkkkkkdknkdpkbkkk\n" +
            "13-15 t: tttttttttttttttt\n" +
            "3-5 p: ppkfkn\n" +
            "4-5 d: dddtk\n" +
            "9-13 b: hbmtbzspcqtwqfkbbbdb\n" +
            "5-7 d: dddtddhdddddddmddddd\n" +
            "6-7 q: qqqqqsl\n" +
            "8-9 k: kkkkkkkkk\n" +
            "3-7 d: gdcwjglkw\n" +
            "6-8 s: srtgjdsn\n" +
            "8-9 r: fxrgqrsrs\n" +
            "5-10 x: xxxxlqxxxxxxxxx\n" +
            "2-3 s: ssskpmzhqpp\n" +
            "2-10 q: qqqqqqqqqqq\n" +
            "5-12 r: srnqrrhkgrjr\n" +
            "1-3 s: fsmsssss\n" +
            "1-2 f: ptbtfm\n" +
            "9-10 b: lbbgrbqhnhbcnmb\n" +
            "1-3 x: xxnx\n" +
            "1-3 w: gjfh\n" +
            "3-8 q: qwqtdvqql\n" +
            "3-5 f: zfmcgpdlp\n" +
            "6-8 h: vhhhhhbh\n" +
            "4-12 c: lkbcvnztjnpxvlcf\n" +
            "4-6 w: wwwwwwwpwwd\n" +
            "10-15 v: vvwvvvdvvzslhvz\n" +
            "4-7 c: jpvmlffcgdkmcl\n" +
            "6-7 l: llllwlll\n" +
            "8-9 m: mmlmlmmnmmm\n" +
            "14-15 m: mmmmmmmmmjnmmmmkz\n" +
            "3-6 t: thttttt\n" +
            "3-14 t: kvltjtmkbvhtbt\n" +
            "6-7 j: jjjjvjjj\n" +
            "5-6 m: dmnmmmknqwmmmkm\n" +
            "8-12 s: ssksssssssssr\n" +
            "2-6 r: srvrqrdwxnprrvpqhd\n" +
            "6-11 l: lhllkdxlllln\n" +
            "2-4 t: qmmd\n" +
            "3-12 s: sssssssssssrs\n" +
            "17-18 t: ttttttttttttttttqf\n" +
            "2-5 r: qcbrr\n" +
            "14-16 h: hhghppchchfhhhlhm\n" +
            "15-17 g: nprhksgfwwjgggkkc\n" +
            "7-8 g: gggggggn\n" +
            "5-15 g: drgkscpgchvzmjs\n" +
            "1-3 l: fsztllllll\n" +
            "4-5 p: ptftp\n" +
            "5-6 j: jjjjjj\n" +
            "1-4 f: ffjfhz\n" +
            "9-10 q: qqtqwslqqg\n" +
            "6-20 h: hgklqhcmhfmxvcnxvxch\n" +
            "7-8 c: jcwbrvcc\n" +
            "8-10 m: mwmmmmmsmvmsf\n" +
            "8-9 v: cfvrvbvzvvvgvpk\n" +
            "14-17 s: srkhgbthtssxszqvsbsx\n" +
            "4-7 b: sbpffpbxv\n" +
            "9-11 z: zzzzzzzzzzzfztz\n" +
            "9-12 v: hmvvvvvvgvhkvvcvvvb\n" +
            "1-6 c: fkcjcwqccs\n" +
            "13-15 r: rrrrrrrrrrrrrrrrrnr\n" +
            "3-4 g: ghgg\n" +
            "6-7 b: wbbbbbbbbbb\n" +
            "7-8 t: trttdtttjbktt\n" +
            "3-4 t: wtttct\n" +
            "2-4 c: xccc\n" +
            "5-7 s: ssspvlrslxn\n" +
            "1-3 s: lsss\n" +
            "4-6 h: hjhjhghh\n" +
            "11-17 s: ssjrsscslskssqssn\n" +
            "1-4 j: rzjjjv\n" +
            "7-8 f: tvssgbrkqdtc\n" +
            "5-8 w: wrjklbblzwdclwnwjwx\n" +
            "4-8 r: srrrrrrr\n" +
            "1-7 g: ggggggg\n" +
            "7-9 m: msmcmmmbwgxkmmnmm\n" +
            "7-10 w: wrwwwvwwww\n" +
            "7-11 g: rgkzgdgpldgc\n" +
            "11-16 p: pppdpzvzpppqrwppv\n" +
            "3-5 n: hnnnnn\n" +
            "10-12 n: nnnnqnnnnmnwnn\n" +
            "6-9 k: spdbkgkxzlqkkkkk\n" +
            "2-5 j: jjjjjjjj\n" +
            "2-4 n: njnzn\n" +
            "7-8 c: cclmcchjcbc\n" +
            "13-16 k: jkrxkmtxfkxfccdklk\n" +
            "8-9 f: fffffffjkfffnpffvfff\n" +
            "8-10 x: xgmdzfxxsc\n" +
            "7-12 k: fknkjrklsrkkkhqknkv\n" +
            "10-12 l: lslzlpllblllll\n" +
            "3-4 f: fffvfff\n" +
            "16-19 j: jjfjjjjjjhjjjjjjjjj\n" +
            "1-3 h: hhhhhhhhhhhhhhw\n" +
            "8-11 n: nnntnpdnvkqt\n" +
            "9-10 n: nnnmnnnnnnnnnn\n" +
            "3-5 c: qbcccchvccf\n" +
            "8-9 s: sssssjsmqj\n" +
            "4-5 w: zwwrxwwfwpwwz\n" +
            "7-9 m: mmmmmmvmf\n" +
            "5-9 w: wwwvtwwwm\n" +
            "11-13 j: zjjjjjjjjjjljjjcjjj\n" +
            "2-9 c: zblcmvmcfc\n" +
            "16-17 g: gggggggggggggggqk\n" +
            "12-15 p: pfcpppsgppxbjvqppppp\n" +
            "4-6 l: ssldtlc\n" +
            "5-8 h: shtphhdhhhhm\n" +
            "17-20 n: nnnnnnnnmnnnnnhnsnnp\n" +
            "12-17 s: sscsrsssdsssssrssss\n" +
            "2-9 j: tjlffpwkjmnj\n" +
            "1-6 p: cpxfpdvjb\n" +
            "10-14 b: bbbbbbbbbhbnbbsbb\n" +
            "3-4 h: hhhnh\n" +
            "1-3 j: rkgjvqkgs\n" +
            "16-17 w: wjwzdwwwwwsxbtlfs\n" +
            "9-11 r: rrrrrrrrrrrr\n" +
            "1-5 d: dtzqdd\n" +
            "5-7 p: pprpppp\n" +
            "6-7 n: nnnnnnn\n" +
            "1-10 k: kkgcklpqzkk\n" +
            "2-4 n: lvxnntjnpwhrsxlnhn\n" +
            "3-6 h: hlhhhxhzh\n" +
            "6-7 c: zccccccc\n" +
            "1-4 z: ztczzzzzzzznzztnlkjz\n" +
            "5-6 c: cccnccshkcpgjhn\n" +
            "3-4 h: hhbh\n" +
            "1-4 m: gmtm\n" +
            "13-18 d: tldhjsdhdthhldzfgjxg\n" +
            "4-5 d: dddddd\n" +
            "1-3 r: rrrr\n" +
            "7-8 b: bbbbbbbt\n" +
            "12-14 z: zzqzbhzzzzzzzz\n" +
            "5-7 v: vqblwrw\n" +
            "8-9 c: tccccdcrccccqc\n" +
            "9-11 m: mmhmmmnmqmtm\n" +
            "3-10 n: dnwzhrfnqt\n" +
            "3-4 t: xnkfpcqtcqkctxrrm\n" +
            "2-7 l: lllllllll\n" +
            "2-7 g: rdnskwgwcgnrzncqtnp\n" +
            "11-13 s: ssssssssssqsw\n" +
            "10-12 m: mmmmmmmmmcmqqmmpmm\n" +
            "4-8 n: gnqnptxnhgpnnnn\n" +
            "6-7 t: tttttcct\n" +
            "2-3 s: sssssss\n" +
            "9-10 h: hhhhhphrms\n" +
            "3-6 d: vdxdddddd\n" +
            "8-15 k: kkkbkkckkkkkkzgkkk\n" +
            "4-10 n: ncntnnnnnnn\n" +
            "3-9 r: snrkcrrcvrx\n" +
            "7-11 s: sssssgwsshks\n" +
            "1-4 h: hfch\n" +
            "10-18 l: llllxllllflllfllsnll\n" +
            "13-16 x: xpwcxpxxxxfqxnxx\n" +
            "2-3 m: mvmmm\n" +
            "3-5 l: ljlzs\n" +
            "8-13 t: tgttttmmrfthttwt\n" +
            "2-9 t: vttjddjxtfrlw\n" +
            "3-5 r: frrrr\n" +
            "4-5 s: pssnm\n" +
            "4-5 h: jcphhsnrm\n" +
            "2-3 d: pjdd\n" +
            "2-3 g: gdgk\n" +
            "10-13 v: svtvvvvvxwvvwv\n" +
            "4-5 l: lqlll\n" +
            "13-14 s: sffbffsmssscss\n" +
            "2-3 j: fkkfmzqjnfvdjr\n" +
            "16-18 z: zmqzzgzkzzzglhzzlzj\n" +
            "3-4 h: hhfh\n" +
            "11-13 s: sssssnsspshswhsssss\n" +
            "7-9 g: gvgggrmgzr\n" +
            "1-5 p: hppxnlkgcpppppppp\n" +
            "1-13 q: qqqqqqqqqlgqqqqqn\n" +
            "3-5 x: xxzxpx\n" +
            "3-15 x: xcndrhtnpbqwgsxtzqn\n" +
            "9-13 d: nrhbddvslmwbs\n" +
            "8-10 g: grggggxggxgg\n" +
            "10-11 h: hrfprqnhbhh\n" +
            "2-3 r: rpzr\n" +
            "14-15 d: ddddddddrdddddd\n" +
            "7-8 b: zbbbbgbbbbpbbv\n" +
            "12-18 v: vvvvvvvvvvvfvvvvvvv\n" +
            "7-13 r: snkkjtnkrntjfd\n" +
            "1-7 g: ngdndgg\n" +
            "1-10 h: hhzhhhhrhhhhhhhh\n" +
            "6-7 x: dxrxxzs\n" +
            "6-7 x: xxxxxxxxxx\n" +
            "8-11 v: vcvvvvxvvkcvlvvvvvv\n" +
            "3-4 n: nrzh\n" +
            "8-12 x: xxxpvxxttxxfmnx\n" +
            "9-10 r: rrrrgrrrzr\n" +
            "2-8 v: lbtvvvzqvzsg\n" +
            "3-5 d: dkfbwlrg\n" +
            "13-14 k: kkkkkkkkkkkkkk\n" +
            "6-8 x: xqgbwxxxppgxz\n" +
            "1-4 n: pnnr\n" +
            "6-9 l: hglpllcnl\n" +
            "1-4 x: xxxx\n" +
            "3-5 n: lnzwmhjnndjdmknnqtnc\n" +
            "8-13 t: tttttttnttttjttt\n" +
            "7-11 s: ssssssssssvbn\n" +
            "1-5 l: lllllll\n" +
            "2-6 v: rvvzvvzcgv\n" +
            "6-8 c: tccckcrc\n" +
            "2-3 q: wnqq\n" +
            "2-3 p: pplpp\n" +
            "3-4 f: kxfwcfsk\n" +
            "1-6 m: mmmmmm\n" +
            "3-4 n: zgnnprvnns\n" +
            "17-18 z: zzzzzzzzzzzzzzzzwhz\n" +
            "3-11 w: wflwwwvwwhrgwwrwwwww\n" +
            "9-13 g: ggggggggpggggg\n" +
            "2-6 r: trvcwrr\n" +
            "5-7 p: prtjptws\n" +
            "7-10 b: bfbjwjlkbsbbwgk\n" +
            "3-5 z: zzzzzzzzwhzzzdznz\n" +
            "4-7 p: lphppppppp\n" +
            "4-5 n: nvnnnsnn\n" +
            "7-9 b: znbhbtgbw\n" +
            "1-11 w: jwwwwwwwwwgw\n" +
            "10-13 w: lwwwwwbwmwwfqwwr\n" +
            "5-12 p: ppppqppppppt\n" +
            "1-10 j: jjpjjjjjjjjjjjjjjj\n" +
            "6-9 g: gxgfgjmggggg\n" +
            "7-12 c: cdccccgcccgc\n" +
            "7-15 m: mmmmmmmmmmmmmmmmmmv\n" +
            "4-7 n: ndwjpvgnh\n" +
            "5-9 s: cszftmnqmssfqs\n" +
            "1-11 m: zmmmcdcmfmdbmltmf\n" +
            "16-17 s: zrshsssxssssssxfs\n" +
            "6-17 m: kphrlmrcmpskjcmmmg\n" +
            "3-4 j: jxjj\n" +
            "2-3 f: ffbfs\n" +
            "4-7 v: vvvvvvvv\n" +
            "1-7 f: fffffffff\n" +
            "1-17 d: dtdftddsdddddddsdd\n" +
            "8-10 c: ccrccccccsc\n" +
            "2-8 m: hqmmmmmpm\n" +
            "2-5 j: jjnjjjj\n" +
            "7-8 s: vsszssssss\n" +
            "3-18 g: ngpggmgggggggggggfgg\n" +
            "14-16 r: rrrkrqrlrrrjrrrpwtr\n" +
            "2-3 h: hshs\n" +
            "10-16 r: mrxdnzxmvrplhmrr\n" +
            "6-7 q: hwqmqqqqqql\n" +
            "3-6 z: rgtqkw\n" +
            "1-13 k: lkkkkkkkkkkkckkk\n" +
            "3-5 t: ttxtt\n" +
            "3-9 s: ljsvzbfwshssrc\n" +
            "6-7 z: zbwzjgw\n" +
            "1-11 n: ptnqltlkrxv\n" +
            "8-9 l: lsllllllhl\n" +
            "2-8 v: vvvvvvvzvvv\n" +
            "5-8 s: ssslnsssssssssl\n" +
            "7-8 k: kpkkkkkchlk\n" +
            "15-18 v: vtvvvvwvvvvvvmvvvb\n" +
            "11-13 m: mqmpjsmmlkvnmnfmwqmq\n" +
            "14-15 k: kkkkkkkkkkkkkljk\n" +
            "13-14 t: tffbtznjgtcnts\n" +
            "5-6 z: kkkpzzctq\n" +
            "4-5 h: jhbhzr\n" +
            "5-7 v: vqvvgxv\n" +
            "6-10 d: dddddpdddtdd\n" +
            "11-12 g: ggggggggggvggg\n" +
            "13-18 f: ffvfffxhrfhrcffpgnff\n" +
            "6-10 x: nsxgwsjxfthhxxgxg\n" +
            "2-5 w: wfvpmwtwg\n" +
            "9-10 l: lljwlllfxcll\n" +
            "2-5 b: rbbbmbbbbbbbbbvbbb\n" +
            "5-13 p: jjffpmbpppmtpf\n" +
            "1-5 r: rrzrrrrkrr\n" +
            "1-2 m: mmmmmgmm\n" +
            "16-18 z: zzzzzzzzzzzgzdzqzz\n" +
            "6-7 l: llwfxll\n" +
            "6-9 j: jjzhjjjjjjj\n" +
            "4-7 k: hwskvkk\n" +
            "2-3 d: dddddq\n" +
            "4-6 b: bbbbbbhbbbbbbbbbbbbb\n" +
            "7-14 l: lnhmlwzxlsldlx\n" +
            "2-4 m: msmmh\n" +
            "4-10 z: vhkrzzcbzzrzdcq\n" +
            "4-7 p: dnppppwp\n" +
            "5-7 z: mzzzzzzz\n" +
            "5-7 b: bbbbbbb\n" +
            "1-5 t: rrbtt\n" +
            "7-11 x: bjxqxtxzlfxpmkpqtnd\n" +
            "7-9 k: kkkkkkkkkk\n" +
            "8-9 d: dhfddpndbhqdtdwdtn\n" +
            "18-19 k: tnkzkdkkkgkkbckkkkk\n" +
            "8-11 f: cfnqkzffgxf\n" +
            "2-4 x: xxwxxsx\n" +
            "8-11 m: mmmkmpcmmvgxmmmcmm\n" +
            "13-14 z: wfzlzzzzzrdxzlzz\n" +
            "2-4 n: frns\n" +
            "4-5 q: qhqqqq\n" +
            "12-18 w: fwwwwdxxzvzzgwpwlk\n" +
            "12-13 n: nnjnnnnnwnnxgnn\n" +
            "8-11 c: tcjcbcwctkccr\n" +
            "4-6 m: jvmhtq\n" +
            "1-2 b: bbbbb\n" +
            "11-12 q: vqfqvqdnsxqq\n" +
            "7-9 m: mgmjmtmmzmmhrm\n" +
            "9-10 t: ktvnttttxl\n" +
            "8-10 r: rcrrdrrdgsrr\n" +
            "7-8 m: bvlmhxfxnlmfbz\n" +
            "3-5 c: bhczc\n" +
            "1-3 w: nwwnwwxww\n" +
            "3-5 l: jcllld\n" +
            "1-10 b: bbtbqbtbbbbtbbbbbbb\n" +
            "5-7 x: vsxxxxxx\n" +
            "3-4 k: gdkv\n" +
            "8-10 k: kpkkwzkrkjkkkm\n" +
            "3-6 l: hhlmll\n" +
            "16-17 x: xxxxxxxxxxxxxtxmx\n" +
            "1-4 w: wrkw\n" +
            "1-4 t: gzpkttttt\n" +
            "2-3 z: zzzq\n" +
            "13-14 q: qqqqqqqqqqqqqq\n" +
            "2-19 d: vdwfzsfqtqbglgrfdvd\n" +
            "4-6 x: dxtnxzx\n" +
            "3-5 g: ggggg\n" +
            "6-7 m: mmmmmjj\n" +
            "15-16 t: tvtttttvbttttttt\n" +
            "5-6 k: kdztgkx\n" +
            "1-3 d: dddd\n" +
            "5-14 h: hhptkkcpqphhdgw\n" +
            "13-14 j: hvmrjdcjhjjfgbmw\n" +
            "10-14 h: hhbhchhhhwhhnhhhthh\n" +
            "2-3 f: jcstlgbdf\n" +
            "3-4 w: kwww\n" +
            "2-12 b: bbbbbbbbbbbfbbbbbbbb\n" +
            "2-4 x: xxxs\n" +
            "10-11 c: qmrtcpztvcc\n" +
            "7-12 l: llptfltlllllzllzl\n" +
            "14-16 m: mmmmmmmmqmmmmtmr\n" +
            "10-18 m: mgmmmnmmbbvmmmmmmgmm\n" +
            "4-18 q: kqlrkhrqljbgwpmpnq\n" +
            "3-4 c: czcdc\n" +
            "2-13 k: jnmzxwvgfldnz\n" +
            "11-12 b: bbbbbbrbbbbb\n" +
            "6-11 p: psfpzrpfpqkzpvppt\n" +
            "9-11 p: mpspjjxcpqpdppppph\n" +
            "4-17 t: tdtftttttttlttdtttwq\n" +
            "12-15 r: krrrrrmrrrrdrrmp\n" +
            "2-3 x: xczx\n" +
            "1-7 j: mjjgjjdjj\n" +
            "2-8 x: jmlxxxxxxxrxxxx\n" +
            "6-7 l: qntxbml\n" +
            "7-12 k: kkkkkkvkkkkfkk\n" +
            "2-7 z: nsgtlfdrsp\n" +
            "7-9 m: mvmmgmjmm\n" +
            "3-7 t: ttttttt\n" +
            "2-9 b: gbczjbbbblbbb\n" +
            "8-12 j: jjjjjjjljjjsj\n" +
            "9-11 h: dmrjmzdwhhhqz\n" +
            "6-10 j: jjjjjjvvjfcp\n" +
            "1-6 t: tqsznxwnnrnmjt\n" +
            "5-8 f: rpffhjnlkxplffhm\n" +
            "8-9 d: fddddddddddcdndddrdd\n" +
            "4-5 k: jkkfckkk\n" +
            "3-5 l: llglkqllll\n" +
            "3-5 k: zkzknkkk\n" +
            "5-7 d: nddddnq\n" +
            "9-10 j: vjgjlfcjjjfxjjmjrzwk\n" +
            "2-4 m: fdxm\n" +
            "5-7 c: cvqgkhvtbccc\n" +
            "7-20 j: rscsdsjzflbldrwqvkjj\n" +
            "4-5 p: pbxpppp\n" +
            "3-4 h: vnhhvlbtbqshhcsxhs\n" +
            "4-12 k: hkdkfxkknkkkkck\n" +
            "4-5 g: gggvq\n" +
            "4-5 h: zhtch\n" +
            "8-12 m: tpmmxzmgmmln\n" +
            "9-15 c: ccckfccjznpclnccxc\n" +
            "9-12 p: pppppppptcpfpppppppp\n" +
            "15-17 g: ttdlnvrknskcgvrgnm\n" +
            "7-12 r: rrrrtrtrrrrjlrrr\n" +
            "4-5 c: rccclxc\n" +
            "3-5 d: hbgzddt\n" +
            "4-5 x: cxxxx\n" +
            "3-4 k: kkpc\n" +
            "8-9 j: jjjjjjjrhv\n" +
            "5-6 p: ppcppp\n" +
            "14-15 h: hqhhhhhghhhhhlrhh\n" +
            "5-10 z: zzzzzzzzzzzzz\n" +
            "6-7 m: mhdmmzpmmmp\n" +
            "1-2 j: knjj\n" +
            "2-7 m: mmqnmjmtkz\n" +
            "2-3 j: jzjjjjj\n" +
            "12-15 g: gggggggggggngggg\n" +
            "6-9 h: hrtllxbqgcrf\n" +
            "3-4 c: ccccc\n" +
            "7-11 g: jclgcjgngkzggg\n" +
            "6-9 s: qwnvpsvbsmwqpqrst\n" +
            "17-18 k: kpdkzkkkkkkkkkfkksk\n" +
            "1-3 v: svnv\n" +
            "4-6 k: kkndkkkkk\n" +
            "12-15 z: zzzzzzzzzzzdzzzz\n" +
            "3-9 z: zzzzzzzzr\n" +
            "7-10 w: vgwwwcwwww\n" +
            "10-15 n: vgxnnnqnnnhwsbnxpnnk\n" +
            "2-4 v: fxhvh\n" +
            "11-12 h: hhjhhhnchhhhhhhh\n" +
            "3-9 z: vzzczzzkzbh\n" +
            "5-8 k: kskkkkktkk\n" +
            "3-7 s: sswssxt\n" +
            "4-7 g: rggdggg\n" +
            "4-7 c: zccpcccc\n" +
            "6-11 z: mzlrssckpzvzslcwzzzz\n" +
            "8-9 v: vvvvvvvvvvvvvv\n" +
            "1-4 f: fffffffffffffffff\n" +
            "8-10 f: tjfffmgrfl\n" +
            "3-5 k: kfwnp\n" +
            "6-7 t: pvtstmq\n" +
            "3-7 x: cvxkwxxgpjxskkvsxp\n" +
            "1-7 c: cctcckccccxc\n" +
            "1-3 g: vfxvfxmhpgg\n" +
            "13-16 m: fmjplfbgzzkrmcmv\n" +
            "3-6 l: llmllc\n" +
            "17-19 j: hjzjrbpjzjdjjvbzjjv\n" +
            "7-12 q: qqqqqqqqqqqq\n" +
            "9-13 n: nnnnnnnnqnnnxnnv\n" +
            "17-18 n: nnnnnnnnnnnnsnnnzh\n" +
            "6-15 f: rswffffffkfffkxfjf\n" +
            "3-6 v: vvvvvvv\n" +
            "9-11 d: ddddddddmdf\n" +
            "19-20 k: kkkkkkkkkkkkhkkkkktg\n" +
            "9-11 f: ffffqfffnfl\n" +
            "6-9 r: rrrrvrrrr\n" +
            "5-6 g: kgdfggggng\n" +
            "17-18 w: wwwwwwwwwwwwwwwwrm\n" +
            "5-14 t: tttttttttttttqtt\n" +
            "13-15 n: nnnbnnnnnnnntnn\n" +
            "4-13 g: rlhgcffsgshcg\n" +
            "4-12 z: mbfztgsbkscpqwl\n" +
            "18-20 p: mmflppmwzscjcgsxdddd\n" +
            "1-6 k: kkkkkkkk\n" +
            "18-19 n: qxkljbmdgsfsnknfhjb\n" +
            "1-2 h: nxnhh\n" +
            "2-11 f: fxffffffffxffffkffff\n" +
            "4-11 k: mqvktsksvkkwjbtvg\n" +
            "13-14 m: kmtmzqmmjmmmmmmwkm\n" +
            "3-5 t: ttswxtt\n" +
            "11-12 b: bbbbbbhbbblbbbb\n" +
            "9-10 w: lkhccgmwvd\n" +
            "2-3 t: thttl\n" +
            "12-13 b: bbbbbbbbbbblb\n" +
            "8-9 w: wdwwjbwblwww\n" +
            "4-5 h: hqphz\n" +
            "9-14 h: hhhhhxhhzhhhhht\n" +
            "9-10 x: xxxxxxxxxxx\n" +
            "4-7 m: dgltmmrdvmfmd\n" +
            "9-10 h: vltrhtgblsmlmnbvml\n" +
            "6-10 p: gkpppbppspp\n" +
            "8-9 c: scjdvbpwn\n" +
            "4-15 f: fpfnffffffffffhn\n" +
            "10-14 s: sssscswsssssss\n" +
            "4-10 j: jxdjfscnmgj\n" +
            "6-12 w: ksjdxwckwwwwwfzwsgz\n" +
            "1-8 j: jjjjjjjtj\n" +
            "1-3 d: kgpvfv\n" +
            "2-12 w: wwwtwwwvwwwwrwwwwww\n" +
            "4-6 f: fkbdftxqtxjwfvf\n" +
            "7-8 p: pppppppk\n" +
            "12-14 g: gmgvgffnggjkgggg\n" +
            "3-4 x: wxkgxxxx\n" +
            "3-7 n: nnnddmcjcrtnnfhnx\n" +
            "4-5 k: kkbmxkk\n" +
            "12-13 b: bbbkxbbbbbnbbtbbgb\n" +
            "9-11 h: hhhhhhhhhhhh\n" +
            "4-6 q: lmgvsfqxmqhvzqqt\n" +
            "13-15 t: ttttvtttttttfhm\n" +
            "1-3 x: hxlw\n" +
            "9-14 v: gjrvgrmvvvdcvv\n" +
            "5-15 z: zzzzczzzzzzzzzzzz\n" +
            "1-8 s: tssssssss\n" +
            "10-15 h: vhvhxthvhhhchhshfh\n" +
            "1-9 l: lllpllqklmlk\n" +
            "12-14 z: zjzzzzzzzhzkzz\n" +
            "3-8 w: wlzzflnmflwdnp\n" +
            "5-7 s: sgsdssss\n" +
            "5-13 h: hnhshhnklhqbhh\n" +
            "4-6 b: xsbbbxbbpbbbbb\n" +
            "14-16 c: cccjgccccccccmvc\n" +
            "5-11 r: nrrrrrrsdjrrk\n" +
            "6-12 s: gssjtjssfhjsssssss\n" +
            "5-6 j: jjjjrs\n" +
            "14-15 d: dddddddddddddddd\n" +
            "10-11 z: zczzzzzzzzzczzzzzz\n" +
            "2-4 q: qqqj\n" +
            "7-13 f: fffffhfffffff\n" +
            "13-14 q: qqqqqqqqqqqqjfqqq\n" +
            "8-9 w: wwwtcwqjw\n" +
            "5-6 x: xcrfxx\n" +
            "13-19 r: rdwfrghfrcnjcdjxtrmr\n" +
            "6-9 h: hhdhhhmlg\n" +
            "7-11 p: ppgpppgppdq\n" +
            "5-6 m: msmrtxm\n" +
            "14-15 j: kjkzrslzdzgrfjjjj\n" +
            "14-15 f: fqjfffwsffzhmff\n" +
            "15-16 d: ddddddddddddddvmdd\n" +
            "10-11 w: wslwwcwkzrvkg\n" +
            "1-3 v: kvvvv\n" +
            "6-12 q: qqqqqbqqqqqzqqqqqq\n" +
            "15-17 m: mmmmmmmmbmmmmmfmxd\n" +
            "1-10 t: sttttttttvt\n" +
            "8-9 q: qqqqqbqwq\n" +
            "14-15 t: ftgtttgftxttwtt\n" +
            "5-9 p: bzkpxnfnj\n" +
            "2-9 h: hhngqknrhd\n" +
            "10-11 h: hhhhbhvhqhhhh\n" +
            "5-8 v: dvstzxwtp\n" +
            "3-5 q: qmzpbmmwsqwzr\n" +
            "7-8 r: rrcrrrrr\n" +
            "3-4 w: wwwt\n" +
            "1-2 l: pzzl\n" +
            "4-13 h: trpbbrhnxnkbrkmgdk\n" +
            "4-5 v: fgxmv\n" +
            "5-11 d: dddgddxrdbmsddj\n" +
            "7-8 s: ssssssss\n" +
            "5-7 m: dfmksgsdmcbjrmk\n" +
            "4-7 s: tsqcssrzs\n" +
            "4-5 j: jjjjjjl\n" +
            "6-10 s: vkwshtpqjxslssxm\n" +
            "3-4 z: zzdfzz\n" +
            "1-5 m: fkhmw\n" +
            "6-11 f: twtfbvwbbsfff\n" +
            "2-9 f: fzwfjljxfxfkjfl\n" +
            "1-2 d: ssddd\n" +
            "5-9 k: kkzkscklbqtkkk\n" +
            "6-16 v: vjfbmnplzwtkxlvdqwn\n" +
            "5-8 g: ggnlkgdh\n" +
            "11-12 s: qbswtxnplqss\n" +
            "3-6 r: rrrrrr\n" +
            "10-11 w: wmhwswwwwfwww\n" +
            "3-9 c: tcncldghxp\n" +
            "3-8 q: wqtqgbpz\n" +
            "17-20 b: bbhblqlbggtsqcbcbbkt\n" +
            "7-15 f: fftffcxgfzttffmbrff\n" +
            "11-12 v: vvvlvrvvwvvqskvvxv\n" +
            "9-11 h: hdjcxnkhxhkqhh\n" +
            "5-12 l: llllqllllllnl\n" +
            "17-18 z: zbzzbzzzzzzzzzzptc\n" +
            "2-6 c: cgmrpjdhkcp\n" +
            "4-10 x: xxxjxtxvxxvx\n" +
            "11-15 s: sspsvsjsssskzbsss\n" +
            "2-4 z: rsfd\n" +
            "4-16 r: rrrrrrlkrrrrrrrrr\n" +
            "10-11 x: xxxxxxxxxpxxxxx\n" +
            "1-10 j: tjjsvjmxcb\n" +
            "4-5 t: tttbbtvttptttsthw\n" +
            "7-11 m: xmxzrnmksbm\n" +
            "2-6 t: vxdspsgtftlptvqft\n" +
            "6-10 k: kkkkmmdkkl\n" +
            "3-5 l: sssglkvfvdskkghdhkxs\n" +
            "4-6 m: mljkmwmnmm\n" +
            "4-7 l: lllllrh\n" +
            "5-11 x: bsmxjxxcmcxxx\n" +
            "1-2 t: tttt\n" +
            "9-11 p: xpppppppcppd\n" +
            "15-16 w: wxzxtwzjrmvkwzdwjt\n" +
            "13-15 l: pnhkxsqfrldsltltcf\n" +
            "4-10 v: vvvrvvvvvvv\n" +
            "6-11 m: qpbmsmbsxpmzg\n" +
            "1-7 m: tmmmlmcmmm\n" +
            "10-14 s: ssshsssscxssszs\n" +
            "1-7 q: tdqxmqkxgkt\n" +
            "2-4 m: bcmq\n" +
            "3-4 d: ddjd\n" +
            "13-17 r: rrrrrrrrvprrrrsrx\n" +
            "3-8 p: fjwbkcdt\n" +
            "1-6 k: gskwbl\n" +
            "7-8 z: wzgzhlzs\n" +
            "5-6 v: xvvvlmvvsvbsv\n" +
            "1-18 f: ffjcfbvrtftffxvfff\n" +
            "3-8 l: lbtjlllqc\n" +
            "4-7 v: vnvvdsvl\n" +
            "15-18 d: ddddpdddddddddcgdrdd\n" +
            "3-9 f: fffffffff\n" +
            "1-5 v: svvjvvlpvwmvvgc\n" +
            "13-14 z: zzzzzzzzzzzzmz\n" +
            "6-8 p: zcwptpgppfpppc\n" +
            "8-14 j: cjrzvhjjmdpzjjqs\n" +
            "16-19 s: sszsssssssssssssssss\n" +
            "7-9 r: rrrkrrrrrnrrmj\n" +
            "2-4 l: ldln\n" +
            "3-5 p: pppvprp\n" +
            "1-5 k: kkkkkk\n" +
            "1-4 g: ggxz\n" +
            "2-4 x: xwsgv\n" +
            "15-16 v: vvvvjvqvfsktgvlvvvv\n" +
            "17-19 x: xxxxxxxxxxxxxxxxcxx\n" +
            "1-8 m: mmmmmhmpmms\n" +
            "2-6 f: lffzdfsf\n" +
            "2-3 p: jphqlvzfmpnmt\n" +
            "2-11 g: ggrjthgdmggkgssq\n" +
            "5-6 r: rwgrrr\n" +
            "4-7 t: tttptmlthlfst\n" +
            "5-7 v: bhhdvhhv\n" +
            "8-11 n: nnnnnnnmnnnnn\n" +
            "7-20 r: rxrqlrwrnrsrrvbvtrrm\n" +
            "9-13 s: pfslddbsshsssrsrssls\n" +
            "3-10 q: vwbwhvdfqqvghjzf\n" +
            "9-14 b: bbbbbbbbbbbbbvb\n" +
            "2-3 f: pfff\n" +
            "3-9 r: trhrrrrrgrrn\n" +
            "7-11 z: zzzzzzzzzzzz\n" +
            "4-6 s: xwssttdqtc\n" +
            "7-9 t: ttzmqqdtqtt\n" +
            "6-19 g: gggggggggggggggggggg";
}
